2024-09-18 03:45:05,888 ERROR: Exception on /index [GET] [in /home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/ubuntu/microblog/app/main/routes.py", line 34, in index
    return render_template('main/index.html', title='Home', form=form, posts=posts.items,
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/main/index.html", line 2, in top-level template code
    {% import "macros/bootstrap_wtf.html" as wtf %}
  File "/home/ubuntu/microblog/app/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ubuntu/microblog/app/templates/main/index.html", line 10, in block 'content'
    {% include '_post.html' %}
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/_post.html", line 15, in template
    username=user_link, when=moment(post.timestamp).fromNow()) }}
jinja2.exceptions.TemplateSyntaxError: expected token ')', got '='
2024-09-18 03:46:52,732 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:72]
2024-09-18 03:46:59,153 ERROR: Exception on /index [GET] [in /home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/ubuntu/microblog/app/main/routes.py", line 34, in index
    return render_template('main/index.html', title='Home', form=form, posts=posts.items,
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/main/index.html", line 2, in top-level template code
    {% import "macros/bootstrap_wtf.html" as wtf %}
  File "/home/ubuntu/microblog/app/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ubuntu/microblog/app/templates/main/index.html", line 10, in block 'content'
    {% include '_post.html' %}
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/_post.html", line 15, in template
    username=user_link, when=moment(post.timestamp).fromNow() }}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2024-09-18 03:49:01,698 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:72]
2024-09-18 03:52:39,688 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:72]
2024-09-23 06:20:31,649 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:72]
