2024-09-08 21:22:41,629 ERROR: Exception on /reset_password_request [GET] [in /home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/microblog/app/routes.py", line 173, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/reset_password_request.html", line 9, in template
    {{ form.email{size=64) }}<br>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '{'
2024-09-08 21:24:44,421 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-08 21:36:21,847 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-09 01:03:42,053 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-09 01:06:28,546 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-09 18:10:42,505 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-10 01:37:27,279 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-10 01:39:07,489 ERROR: Exception on /index [GET] [in /home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/ubuntu/microblog/app/routes.py", line 34, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items,
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/index.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/ubuntu/microblog/app/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ubuntu/microblog/app/templates/index.html", line 5, in block 'content'
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
2024-09-10 01:40:45,363 INFO: Microblog startup [in /home/ubuntu/microblog/app/__init__.py:45]
2024-09-10 01:40:52,119 ERROR: Exception on /index [GET] [in /home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/ubuntu/microblog/app/routes.py", line 34, in index
    return render_template('index.html', title='Home', form=form, posts=posts.items,
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/ubuntu/microblog/app/templates/index.html", line 2, in top-level template code
    {% import "_macros.html" as macros %}
  File "/home/ubuntu/microblog/app/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/home/ubuntu/microblog/app/templates/index.html", line 5, in block 'content'
    <h1>{{ _('Hi, _%(username)s!', username=current_user.username) }}</h1>
  File "/home/ubuntu/microblog/venv/lib/python3.10/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: '_' is undefined
